import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { sankaRoutes } from './providers/sanka/sanka.routes.js';
import { meRoutes, userRoutes } from './routes/me.routes.js';
import { watchRoutes } from './routes/watch.routes.js';
import { leaderboardRoutes } from './routes/leaderboard.routes.js';
import { sankaClient } from './providers/sanka/sanka.client.js';
import { requireAuth } from './middleware/auth.js';
import { config } from './utils/config.js';
import { AppError } from './utils/errors.js';
import { fail, ok } from './utils/response.js';

const app = new Hono();
app.use('*', cors({ origin: (origin) => config.corsOrigins.includes('*') ? '*' : (origin && config.corsOrigins.includes(origin) ? origin : config.corsOrigins[0] ?? '*'), allowHeaders: ['Content-Type', 'Authorization'], allowMethods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS'] }));
app.get('/api/health', (c) => c.json({ success: true, status: 'online' }));
app.route('/api/anime', sankaRoutes);
app.get('/api/anime/:slug', async (c) => ok(c, await sankaClient.get(`/anime/anime/${encodeURIComponent(c.req.param('slug'))}`)));
app.get('/api/episode/:slug', async (c) => ok(c, await sankaClient.get(`/anime/episode/${encodeURIComponent(c.req.param('slug'))}`)));
app.get('/api/stream/:serverId', async (c) => ok(c, await sankaClient.get(`/anime/server/${encodeURIComponent(c.req.param('serverId'))}`)));
app.route('/api/me', meRoutes);
app.use('/api/history', requireAuth);
app.use('/api/history/*', requireAuth);
app.use('/api/favorites', requireAuth);
app.use('/api/favorites/*', requireAuth);
app.route('/api', userRoutes);
app.route('/api/watch', watchRoutes);
app.route('/api/leaderboard', leaderboardRoutes);
app.notFound((c) => fail(c, 'NOT_FOUND', 'Route not found', 404));
app.onError((error, c) => { const appError = error instanceof AppError ? error : new AppError(error.name?.toLowerCase().includes('firebase') ? 'FIREBASE_ERROR' : 'INTERNAL_ERROR', 'Internal server error', 500); return fail(c, appError.code, appError.message, appError.status); });
export default app;
